### ISSUE TITLE
docker swarm部署后看不到界面

### ISSUE THREAD

**Issue by aotsukiqx** [labring/FastGPT#1006]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
在docker swarm部署，使用外部pgvector和mongo，两个服务正常为其他应用提供服务。
fastgpt容器启动后看不到任何报错，只有如下日志内容，容器状态也始终正常，但是无法访问映射端口。
  ▲ Next.js 13.5.2
  - Local:        http://0692b2bd9f37:3000
  - Network:      http://172.33.16.9:3000
 ✓ Ready in 126ms

**复现步骤**
docker swarm环境，新建stack只部署一个service
```yaml
version: '3.3'
services:
  fastgpt:
    image: ghcr.io/labring/fastgpt:latest # git
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/fastgpt:latest # 阿里云
    ports:
      - 3003:3000
    environment:
      # root 密码，用户名为: root
      - DEFAULT_ROOT_PSW=123456
      # 中转地址，如果是用官方号，不需要管。务必加 /v1
      - OPENAI_BASE_URL=http://myapi.domain.com:3200
      - CHAT_API_KEY=sk-xxxx
      - DB_MAX_LINK=5 # database max link
      - TOKEN_KEY=any
      - ROOT_KEY=root_key
      - FILE_TOKEN_KEY=akey
      # mongo 配置，不需要改. 用户名myusername,密码mypassword。
      - MONGODB_URI=mongodb://fastgpt:j734562@mongodb1.com:27017/fastgpt?authSource=admin
      # pg配置. 不需要改
      - PG_URL=postgresql://fastgpt:i45g8eh4up@pgvector1.com:5433/fastgpt
    volumes:
      - /mnt/nfsconfs/confs/fastgpt/confile/config.json:/app/data/config.json
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.name == a1]
```
**预期结果**
可以打开界面正常使用
**相关截图**
