### ISSUE TITLE
本地运行的FastGPT无法连接docker里的mongo和pg容器

### ISSUE THREAD

**Issue by WestCraneLi** [labring/FastGPT#1072]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: lateset

**问题描述**
* 运行环境：本机 Mac OS Intel + 本机 Docker
* 模型服务：文心一言Speed + 文心一言向量模型bge-large-zh
* 考虑到已经在docker部署了FastGPT，包括FastGPT前端项目+mongo+pg，mongo初始化副本集也是成功的，联通也是正常包括登录，上传知识库和机器人聊天，于是想让本地的FastGPT前端项目链接docker里的mongo容器和pg容器，这样节省了在本地安装mongo+pg的过程，但是无法链接
![image](https://github.com/labring/FastGPT/assets/76116480/059e9d20-b735-49eb-8c62-fed2710db0d9)
* 本地FastGPT登录报错
![image](https://github.com/labring/FastGPT/assets/76116480/64e4692a-8098-4f57-9504-8459d926dbde)
* One-Api是正常运行的，也可以联通

**复现步骤**
* FastGPT文件权限分配+依赖下载，可以正常启动
![image](https://github.com/labring/FastGPT/assets/76116480/da5935ad-1827-4c07-80a1-cc1d8bc6fce1)
* 添加.env.local，在这个步骤中，本地可以ping通mongo容器和pg容器，同时容器里也能ping通本机，端口也是开放，没有冲突，而且链接的主机名尝试替换过`本地主机名10.0.9.248`、`127.0.0.1`、`localhost`
```bash
# .env.local
LOG_DEPTH=3
# 默认用户密码，用户名为 root，每次重启时会自动更新。
DEFAULT_ROOT_PSW=123456
# 数据库最大连接数
DB_MAX_LINK=5
# token
TOKEN_KEY=dfdasfdas
# 文件阅读时的秘钥
FILE_TOKEN_KEY=filetokenkey
# root key, 最高权限
ROOT_KEY=fdafasd
# openai 基本地址，可用作中转。
OPENAI_BASE_URL=http://10.0.9.248:8089/v1
# oneapi 地址，可以使用 oneapi 来实现多模型接入
# ONEAPI_URL=https://xxxx.cloud.sealos.io/openai/v1
# 通用key。可以是 openai 的也可以是 oneapi 的。
# 此处逻辑：优先走 ONEAPI_URL，如果填写了 ONEAPI_URL，key 也需要是 ONEAPI 的 key
CHAT_API_KEY=sk-xxxxx
# mongo 数据库连接参数，本地开发时，mongo可能需要增加 directConnection=true 参数，才能连接上。
MONGODB_URI=mongodb://myusername:mypassword@10.0.9.248:27017/fastgpt?authSource=admin
# PG 数据库连接参数
PG_URL=postgresql://username:password@10.0.9.248:5433/postgres
# 商业版地址
PRO_URL=
# 首页路径
HOME_URL=/
# Loki Log Path
# LOKI_LOG_URL=
```
* docker-compose.yml配置，这块几乎和官方一致，除了端口和API地址和API KEY
```yml
# 非 host 版本, 不使用本机代理
# (不懂 Docker 的，只需要关心 OPENAI_BASE_URL 和 CHAT_API_KEY 即可！)
version: '3.3'
services:
  pg:
    image: ankane/pgvector:v0.5.0 # git
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/pgvector:v0.5.0 # 阿里云
    container_name: pg
    restart: always
    ports: # 生产环境建议不要暴露
      - 5433:5432
    networks:
      - fastgpt
    environment:
      # 这里的配置只有首次运行生效。修改后，重启镜像是不会生效的。需要把持久化数据删除再重启，才有效果
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - ./pg/data:/var/lib/postgresql/data
  mongo:
    image: registry.cn-hangzhou.aliyuncs.com/fastgpt/mongo:5.0.18
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
        - fastgpt
    command: mongod --keyFile /data/mongodb.key --replSet rs0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myusername
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - ./mongo/data:/data/db
    entrypoint:
      - bash
      - -c
      - |
        openssl rand -base64 128 > /data/mongodb.key
        chmod 400 /data/mongodb.key
        chown 999:999 /data/mongodb.key
        exec docker-entrypoint.sh $$@
  fastgpt:
    container_name: fastgpt
    image: ghcr.io/labring/fastgpt:latest # git
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/fastgpt:latest # 阿里云
    ports:
      - 3001:3000
    networks:
      - fastgpt
    depends_on:
      - mongo
      - pg
    restart: always
    environment:
      # root 密码，用户名为: root
      - DEFAULT_ROOT_PSW=123456
      # 中转地址，如果是用官方号，不需要管。务必加 /v1
      - OPENAI_BASE_URL=http://10.0.9.248:88089/v1
      - CHAT_API_KEY=sk-xxxxx
      - DB_MAX_LINK=5 # database max link
      - TOKEN_KEY=any
      - ROOT_KEY=root_key
      - FILE_TOKEN_KEY=filetoken
      # mongo 配置，不需要改. 用户名myusername,密码mypassword。
      - MONGODB_URI=mongodb://myusername:mypassword@mongo:27017/fastgpt?authSource=admin
      # pg配置. 不需要改
      - PG_URL=postgresql://username:password@pg:5432/postgres
    volumes:
      - ./config.json:/app/data/config.json
networks:
  fastgpt:
```
* 初始化mongo副本集
![image](https://github.com/labring/FastGPT/assets/76116480/c6433e98-a3e5-4ada-a788-d502302eed46)
* 登录本地FastGPT
  * 用户名密码：root 123456
![image](https://github.com/labring/FastGPT/assets/76116480/e556fe12-3026-4cbc-94dc-3d4c0fc37029)
![image](https://github.com/labring/FastGPT/assets/76116480/54bc8a8f-ae4b-490b-98a1-9f5175289725)

**预期结果**
本地FastGPT运行成功后，登录后进入聊天页面

**相关截图**

**Comment by c121914yu** [comment]
# mongo 数据库连接参数，本地开发时，mongo可能需要增加 directConnection=true 参数，才能连接上。
~env里不是提示你这个么

**Comment by WestCraneLi** [comment]
好像不行，刚刚加上了
![image](https://github.com/labring/FastGPT/assets/76116480/c4ffe05f-36eb-48d4-ae63-5e27594f0b98)

**Comment by meast** [comment]
https://doc.fastai.site/docs/development/docker/

rs.initiate 的时候，你是按文档上直接用的吧， host: "mongo:27017" 这个可能要改成 ip:27017 。

**Comment by WestCraneLi** [comment]
> https://doc.fastai.site/docs/development/docker/
> 
> rs.initiate 的时候，你是按文档上直接用的吧， host: "mongo:27017" 这个可能要改成 ip:27017 。

似乎不行
![image](https://github.com/labring/FastGPT/assets/76116480/75258505-2773-4ae3-8383-68a4011a6279)

**Comment by c121914yu** [comment]
那基本可以确定，是你端口问题了

**Comment by WestCraneLi** [comment]
![image](https://github.com/labring/FastGPT/assets/76116480/6ea3b309-16cb-4bfb-896e-722065ff13ae)
我新启了一个容器，docker-compose.yml和官方一致，但改动了端口和去除network和去除fastgpt
```yml
# 非 host 版本, 不使用本机代理
# (不懂 Docker 的，只需要关心 OPENAI_BASE_URL 和 CHAT_API_KEY 即可！)
version: '3.3'
services:
  pg:
    image: ankane/pgvector:v0.5.0 # git
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/pgvector:v0.5.0 # 阿里云
    container_name: local-pg
    restart: always
    ports:
      # 生产环境建议不要暴露
      - 5435:5432
    environment:
      # 这里的配置只有首次运行生效。修改后，重启镜像是不会生效的。需要把持久化数据删除再重启，才有效果
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - ./pg/data:/var/lib/postgresql/data
  mongo:
    image: registry.cn-hangzhou.aliyuncs.com/fastgpt/mongo:5.0.18
    container_name: local-mongo
    restart: always
    ports:
      - 27019:27017
    command: mongod --keyFile /data/mongodb.key --replSet rs0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myusername
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - ./mongo/data:/data/db
    entrypoint:
      - bash
      - -c
      - |
        openssl rand -base64 128 > /data/mongodb.key
        chmod 400 /data/mongodb.key
        chown 999:999 /data/mongodb.key
        exec docker-entrypoint.sh $$@
```
.env.local
```env
LOG_DEPTH=3
# 默认用户密码，用户名为 root，每次重启时会自动更新。
DEFAULT_ROOT_PSW=123456
# 数据库最大连接数
DB_MAX_LINK=5
# token
TOKEN_KEY=dfdasfdas
# 文件阅读时的秘钥
FILE_TOKEN_KEY=filetokenkey
# root key, 最高权限
ROOT_KEY=fdafasd
# openai 基本地址，可用作中转。
OPENAI_BASE_URL=http://10.0.9.247:8089/v1
# oneapi 地址，可以使用 oneapi 来实现多模型接入
# ONEAPI_URL=https://xxxx.cloud.sealos.io/openai/v1
# 通用key。可以是 openai 的也可以是 oneapi 的。
# 此处逻辑：优先走 ONEAPI_URL，如果填写了 ONEAPI_URL，key 也需要是 ONEAPI 的 key
CHAT_API_KEY=sk-4dydg4agHur7EJVF7aA7D6B03b1342F49fEf4177B22742Ac-1
# mongo 数据库连接参数，本地开发时，mongo可能需要增加 directConnection=true 参数，才能连接上。
MONGODB_URI=mongodb://myusername:mypassword@10.0.9.247:27019/fastgpt?authSource=admin?directConnection=true
# PG 数据库连接参数
PG_URL=postgresql://username:password@10.0.9.247:5435/postgres
# 商业版地址
PRO_URL=
# 首页路径
HOME_URL=/
# Loki Log Path
# LOKI_LOG_URL=
```

初始化mongo
![image](https://github.com/labring/FastGPT/assets/76116480/88a2776f-d7a5-4695-a6da-848393ee6fdc)

请问是哪里的端口问题呢
