### ISSUE TITLE
如何正确配置Nginx？

### ISSUE THREAD

**Issue by taowang1993** [labring/FastGPT#2885]
我想在云端部署docker-compose-milvus.yaml
请问，以下配置是否正确？我想把Nginx容器加入docker-compose-milvus.yaml
ssl证书，我用的是Cloudflare Original Certificates

```
version: '3.8'

services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # 绑定本地配置文件
      - /path/to/certificates/:/etc/nginx/certificates/  # 绑定证书目录
    depends_on:
      - milvus

## 其他services
```

nginx.conf
```
events {}

http {
    server {
        listen 80;
        server_name your_domain.com;  # 替换为你的域名

        # 将 HTTP 请求重定向到 HTTPS
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name your_domain.com;  # 替换为你的域名

        ssl_certificate /etc/nginx/certificates/fullchain.pem;  # 替换为你的证书路径
        ssl_certificate_key /etc/nginx/certificates/privkey.pem;  # 替换为你的私钥路径

        location / {
            proxy_pass http://milvus:19530;  # 代理到 Milvus 服务
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}

```

作者可否分享一下，云端应用（https://cloud.tryfastgpt.a）的Nginx配置方法？

十分感谢！
