### ISSUE TITLE
[bug] When issuing instructions to qwen from the webui of fastgpt, docker reports a Connection error.

### ISSUE THREAD

**Issue by willwilling** [labring/FastGPT#722]
<img width="705" alt="b53a9dec187ca6050f46b4141802fc2" src="https://github.com/labring/FastGPT/assets/18168678/27f50f08-169e-43ce-b720-09fb4bdfd1ef">

<img width="713" alt="8b43be99dbac0dff8166a3bdd70158d" src="https://github.com/labring/FastGPT/assets/18168678/684063f7-9434-4702-b163-25cf1db29b0b">

**Comment by c121914yu** [comment]
网络不通。容器里127.0.0.1指向自身，不指向本机。

**Comment by willwilling** [comment]
还是不行  在docker中ping 127.0.0.1:13000是OK的，但是还是不通。
![image](https://github.com/labring/FastGPT/assets/18168678/76b09421-43a6-4ac6-952d-8536a3570d30)

**Comment by willwilling** [comment]
我尝试用13000端口链接one api
![image](https://github.com/labring/FastGPT/assets/18168678/2a415391-b0d8-45ba-a0cc-acb94e720162)

**Comment by kitaev-chen** [comment]
用 docker 容器自己的网络:

1. 查看有哪些网络，默认 one-api 和 fastgpt 肯定在不同的网络
```
docker network ls
```

2. 一个解决方案就是 fastgpt 的 compose 文件配置 one-api 的 network 名，再加 external: true
```
    networks:
      - one-api_default
      # - fastgpt

...
           - OPENAI_BASE_URL=http://one-api:3000/v1
...
networks:
  one-api_default:
    external: true
```

3. 另一个解决方案是将两个不同网络连起来
```
docker network connect one-api_default fastgpt
```
